apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: submit
spec:
  template:
#    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: git-push
      eventSourceName: github
      eventName: push
  triggers:
    - template:
        conditions: "git-push"
        name: trigger-namespace
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: submit-namespaced-
              spec:
                workflowTemplateRef:
                  name: demo-workflow-template
    - template:
        conditions: "git-push"
        name: trigger-cluster
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: submit-cluster-
              spec:
                workflowTemplateRef:
                  name: demo-workflow-template2


